### ISSUE TITLE
addRolesForUser批量新增不成功

### ISSUE THREAD

**Issue by lvtu1124** [php-casbin/laravel-authz#10]
addRolesForUser返回true，实际没写入，addRoleForUser是可以的，追踪看到
` 
 private function updateWatcher(): void
    {
        if (!is_null($this->watcher) && $this->autoNotifyWatcher) {
            $this->watcher->update();
        }
   }
`
里面$this->watcher为空，帮忙看看是不是bug，还是说需要哪里调用才启动批量插入

**Comment by hsluoyz** [comment]
@basakest

**Comment by hsluoyz** [comment]
@lvtu1124 fixed in: https://github.com/php-casbin/laravel-authz/pull/11

@techoner @basakest please make a new release.
