### ISSUE TITLE
[Question] Loading model from a remote URL

### ISSUE THREAD

**Issue by francoisauclair911** [php-casbin/laravel-authz#15]
Hi,

I'm storing my model.conf remotly and would like to fetch it at runtime(and eventually cache it)

I see that the config has a load from string option, I'm wondering how (where) one would set up request call to the model URL and then load the model as string.

Thank you

**Comment by hsluoyz** [comment]
@basakest 

/cc @techoner

**Comment by hsluoyz** [comment]
Not planned.

@leeqvip this issue can be closed now

**Comment by leeqvip** [comment]
Fixed by #69
