### ISSUE TITLE
Call to undefined method Casbin\\Enforcer::buildIncrementalRoleLinks()

### ISSUE THREAD

**Issue by rus-ik** [php-casbin/laravel-authz#26]
Starting from v2.2.0 I'm getting the following error while executing Enforcer::deleteRoleForUser

Call to undefined method Casbin\\Enforcer::buildIncrementalRoleLinks()\n#0 /var/www/html/vendor/casbin/casbin/src/ManagementEnforcer.php(582): Casbin\\InternalEnforcer->removePolicyInternal()\n#1 /var/www/html/vendor/casbin/casbin/src/ManagementEnforcer.php(540): Casbin\\ManagementEnforcer->removeNamedGroupingPolicy()\n#2 /var/www/html/vendor/casbin/casbin/src/Enforcer.php(100): Casbin\\ManagementEnforcer->removeGroupingPolicy()\n#3 /var/www/html/app/Observers/Auth/UserAccessGroupObserver.php(65): Casbin\\Enforcer->deleteRoleForUser()\n#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(412):
...
casbin/casbin version is v3.6.0

If it's difficult to implement, then it seems "require" in composer.json is not quite correct..

"require" : {
  "casbin/casbin": "~3.1",
 ...
}

**Comment by hsluoyz** [comment]
@basakest

**Comment by basakest** [comment]
I tried to use the corresponding version of the composer package to reproduce this error, but I got another error, the error message is as follows: Class Lauthz\Adapters\DatabaseAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Casbin\Persist\UpdatableAdapter::updatePolicies). Can you provide some other information?
<img width="1404" alt="Screen Shot 2021-07-29 at 10 04 05 AM" src="https://user-images.githubusercontent.com/47746206/127420641-3dfa0db4-2938-4199-ae2a-9e75e8b868c8.png">
<img width="743" alt="Screen Shot 2021-07-29 at 10 04 37 AM" src="https://user-images.githubusercontent.com/47746206/127420658-ad4223d2-344c-45f9-9a9c-ed3b6de62ec9.png">
<img width="1178" alt="Screen Shot 2021-07-29 at 10 05 27 AM" src="https://user-images.githubusercontent.com/47746206/127420667-3edb49f8-fc93-4028-8914-09b34539bb67.png">

**Comment by hsluoyz** [comment]
@techoner

**Comment by rus-ik** [comment]
Any ETA of the bugfix, guys?

**Comment by rus-ik** [comment]
hey guys, the problem is that .. the minimal workable version of laravel-authz (it seems it was v1.4 or 1.5, which worked fine w/o the error mentioned above) is not working with the latest laravel v8.. 
and since we're moved forward to v8 we cannot downgrade to make everything to work fine again like it was..

So can you please either catchup in v1.5 to laravel v8 or to fix the bug in the latest version..
Thanks in advance!

![image](https://user-images.githubusercontent.com/743185/128480192-cbffb2c3-a172-4d25-853e-dcf63c2315d3.png)

**Comment by hsluoyz** [comment]
@basakest

**Comment by techoner** [comment]
@rus-ik Can you upgrade laravel-authz to the latest version([v2.4.0](https://github.com/php-casbin/laravel-authz/releases/tag/v2.4.0))?

**Comment by rus-ik** [comment]
It seems it's a tricky bug:
![image](https://user-images.githubusercontent.com/743185/128520511-bb03a1c7-69f0-4972-a8fd-6a7c78e93ca3.png)

**Comment by rus-ik** [comment]
here is my model.conf:

[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)

**Comment by basakest** [comment]
I'm sorry, but I still haven't been able to reproduce this error
<img width="1408" alt="Screen Shot 2021-08-07 at 11 48 29 AM" src="https://user-images.githubusercontent.com/47746206/128586976-f8d792cf-54b9-4266-9c3c-7dcd41be6fa3.png">

**Comment by hsluoyz** [comment]
@rus-ik can you provide a fully reproducible code repo?

**Comment by rus-ik** [comment]
Sorry guys, it turned out that we had overloaded casbin classes (mainly to suppress the not controlled logging) and after the right upgrade everything works fine. Thank you for your time and attention!

But nonetheless, it'd be great to have any feature for the logging switching in the places like this one:
https://github.com/php-casbin/php-casbin/blob/master/src/CoreEnforcer.php#L365

And to have a short, one-line logging like this one, out of the box:
...
[2021-08-08 11:00:10] prod.INFO: DENIED 212.118.111.222 - o.ivanov@mail.ru "GET" "/api/v1/role1/users" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36"
...

/**
 * Class DefaultLogger.
 *
 * @author techlee@qq.com
 */
class DefaultLogger implements Logger
{
    const LOG_CHANNEL = 'stdout';
    const LOG_IDENTIFIER = 0;
    const LOG_ROUTE = 1;
    const LOG_METHOD = 2;
    const LOG_BROWSER = 3;
    const LOG_IP = 4;
    const LOG_RESULT = 5;
...
    /**
     * @param mixed ...$v
     */
    public function write(...$v): void
    {
        if ($this->enable && ($v[0] ?? false)) {
            $this->save($this->prepareLogArray($v[0]));
        }
    }

    /**
     * @param array $log
     * @return string
     */
    public function prepareLogArray(array $log): string
    {
        return ($log[self::LOG_RESULT] ? 'GRANTED' : 'DENIED') . ' '.$log[self::LOG_IP].' - '.$log[self::LOG_IDENTIFIER].' "'.$log[self::LOG_METHOD].'" '.'"'.$log[self::LOG_ROUTE].'" '.'"'.$log[self::LOG_BROWSER].'"';
    }
...

**Comment by hsluoyz** [comment]
@rus-ik can you make a PR?

**Comment by rus-ik** [comment]
I will, but .. not now..
