### ISSUE TITLE
must therefore be declared abstract or implement the remaining methods 

### ISSUE THREAD

**Issue by pandelix** [php-casbin/laravel-authz#27]
Symfony\Component\ErrorHandler\Error\FatalError: Class Lauthz\Adapters\DatabaseAdapter contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Casbin\Persist\UpdatableAdapter::updatePolicies) in file /web_root/vendor/casbin/laravel-authz/src/Adapters/DatabaseAdapter.php on line 23

**Comment by techoner** [comment]
@basakest

**Comment by techoner** [comment]
@pandelix Can you upgrade to the latest version to see if the problem exists?
