### ISSUE TITLE
Too few arguments to function Illuminate\\Database\\Eloquent\\Model::fireModelEvent(), 0 passed in /site/zhihuiyuanqu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1634 and at least 1 expected

### ISSUE THREAD

**Issue by hei0323** [php-casbin/laravel-authz#34]
When I execute code“  Enforcer::deletePermissionsForUser($sub);”，it make an error;

**Comment by techoner** [comment]
@hei0323 Which version of Laravel-authz are you using ?
Can you delete the `vendor` directory and install it again using `composer install`?
