### ISSUE TITLE
Argument 1 passed to Casbin\Rbac\DefaultRoleManager\RoleManager::hasLink() must be of the type string, int given, called in /var/www/html/amitdeveloper28/vendor/casbin/casbin/src/Util/BuiltinOperations.php on line 440

### ISSUE THREAD

**Issue by amitgoldy1** [php-casbin/laravel-authz#36]
I am getting this issue, when I used following steps to reproduce this issue.

1. I am using laravel Laravel Framework 6.20.38.
2. add  permission of logged user in laravel. Below are my code:   $email = Auth::user()->email;
        // adds permissions to a user
        \Enforcer::addPermissionForUser($email, '/photo/index', 'GET');
3. When, I hit this allow path, I am getting this error:
4. Argument 1 passed to Casbin\Rbac\DefaultRoleManager\RoleManager::hasLink() must be of the type string, int given, called in /var/www/html/amitdeveloper28/vendor/casbin/casbin/src/Util/BuiltinOperations.php on line 440

**Comment by hsluoyz** [comment]
@basakest @techoner

**Comment by basakest** [comment]
Is the configuration file you use the built-in lauthz-rbac-model.conf? I try to reproduce this error, but no success. 
<img width="813" alt="Screen Shot 2021-11-14 at 10 54 23 AM" src="https://user-images.githubusercontent.com/47746206/141665642-14884e0f-f504-4e67-a8b4-cbac3a51d9ec.png">

**Comment by basakest** [comment]
Are you using the default lauthz-rbac-model.conf configuration file? I tried to reproduce this error, but did not succeed.

**Comment by amitgoldy1** [comment]
Yes, I am using default model file. Below are the code:
========================================
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && keyMatch2(r.obj, p.obj) && regexMatch(r.act, p.act)

**Comment by amitgoldy1** [comment]
**I am using this middleware in web.php file.**

Route::group(['middleware' => ['http_request']], function () {
    Route::resource('photo', 'PhotoController');
});

**Comment by techoner** [comment]
@basakest @amitgoldy1 There should be a need to convert the AuthIdentifier to a string ：
https://github.com/php-casbin/laravel-authz/blob/master/src/Middlewares/RequestMiddleware.php#L53

**Comment by hsluoyz** [comment]
@basakest plz work on it
