### ISSUE TITLE
I hope it can be used under the lumen project at the same time?

### ISSUE THREAD

**Issue by dafa168** [php-casbin/laravel-authz#38]
强烈希望可以同时在lumen项目下使用， 目前我们公司项目大多数都采用的是lumen框架搭建的；
 在安装php-casbin/laravel-authz的时候会报错，提示：必须在laravel上才能使用；
强制安装上之后，发现Laravel框架核心也被安装上了， 这样会导致项目vendor目录非常大。
所以希望发个能在lumen上使用的版本，谢谢。

**Comment by hsluoyz** [comment]
@techoner can we create a new repo?

**Comment by dafa168** [comment]
> 

其实没有必要新建一个仓库。 
1、去掉必须要laravel核心的条件；
2、在ServiceProvider中兼容lumen；
3、在使用方法中，增加关于lumen的使用方法；
4、最好不和Auth::User() 做强耦合。

**Comment by techoner** [comment]
@dafa168 Can you make a PR ?

**Comment by hsluoyz** [comment]
@basakest

**Comment by dafa168** [comment]
> @dafa168 Can you make a PR ?

非常抱歉，最近工作非常忙。

**Comment by hsluoyz** [comment]
@basakest can you work on this?

**Comment by phpxcn** [comment]
请问lumen可用的版本什么时候能发布呢

**Comment by leeqvip** [comment]
@phpxcn  Maybe a week or more.

**Comment by leeqvip** [comment]
@dafa168 @phpxcn The latest version is already compatible with `lumen` .

**Comment by hsluoyz** [comment]
See: https://github.com/php-casbin/laravel-authz/releases/tag/v3.1.0
