### ISSUE TITLE
update to use casbin v2.3.0

### ISSUE THREAD

**Issue by rus-ik** [php-casbin/laravel-authz#4]
Can you please use casbin not lower than v2.3.0, where 'eval' in ABAC policy has been introduced.

**Comment by techoner** [comment]
You can use `composer udpate`

**Comment by hsluoyz** [comment]
@techoner I think he means to update composer.json to v2.3.0?

https://github.com/php-casbin/laravel-authz/blob/ec12e524aec6d8547fe7c15b127d073e491f3d6d/composer.json#L25

**Comment by techoner** [comment]
`Laravel-auth` supports version 2.0 and above, he can specify a specific version in his own project, for example: "casbin / casbin": "2.3. *",

**Comment by rus-ik** [comment]
Guys, have you ever tried to add into composer.json what you're writing about?

"require" : {
    ...
    "casbin/casbin": "^2.3",
    ...
and then discover:

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package casbin/casbin ^2.3 exists as casbin/casbin[1.x-dev, dev-analysis-XZpnE0, dev-master, v0.1, v0.1.1, v0.1.2, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.2, v0.2.1, v1.0.0, v1.0.1, v1.0.2, v1.0.3, v2.0.0, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.2.0] but these are rejected by your constraint.
  Problem 2
    - casbin/laravel-authz v1.4.0 requires casbin/casbin ~2.0 -> satisfiable by casbin/casbin[v2.0.0, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.2.0] but these conflict with your requirements or minimum-stability.
    - casbin/laravel-authz v1.4.0 requires casbin/casbin ~2.0 -> satisfiable by casbin/casbin[v2.0.0, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.2.0] but these conflict with your requirements or minimum-stability.
    - Installation request for casbin/laravel-authz ^1.4 -> satisfiable by casbin/laravel-authz[v1.4.0].

**Comment by techoner** [comment]
The latest version of PHP-casbin is V2.2:

**Comment by rus-ik** [comment]
yeah, so can we have an option to start using "casbin/casbin": "dev-master". Thanks in advance
