### ISSUE TITLE
Lauthz\Facades\Enforcer has no type hints

### ISSUE THREAD

**Issue by lanrenbulan** [php-casbin/laravel-authz#43]
Hi,

Lauthz\Facades\Enforcer has no type hints.

It is recommended to add @method static.

`namespace Lauthz\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * @see \Casbin\Enforcer
 * @method static array getPermissionsForUser
 */
class Enforcer extends Facade
{`

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by lanrenbulan** [comment]
I submitted a PR to fix this, please review.

**Comment by hsluoyz** [comment]
@leeqvip plz close this issue, as fixed by: https://github.com/php-casbin/laravel-authz/pull/45
