### ISSUE TITLE
New feature proposal

### ISSUE THREAD

**Issue by RafGiammario** [php-casbin/laravel-authz#48]
Now in laravel-authz the artisan commands are really cool and useful and maybe can be make more generic.

For example, I have this situation for my roles:

`
[role_definition]
g = _, _
g2 = _, _
g3 = _, _, _
`
So I ask if it's possible to extends artisan command role:assign to take g,g1,g3 as type parameter, to make easier to insert roles.

Thanks

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@RafGiammario  Good idea, we will implement it asap. You can submit a PR if you can.

**Comment by leeqvip** [comment]
@M1serry
