### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by lanrenbulan** [php-casbin/laravel-authz#49]
Hi,

Is this library still being maintained?

**Comment by hsluoyz** [comment]
@lanrenbulan yes, is there any issue you have encountered?

**Comment by lanrenbulan** [comment]
@hsluoyz A new version has not been released for a long time. A PR with new Enforcer annotation was proposed before, but the new version has never been released.

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@lanrenbulan It has been released in the latest version.
