### ISSUE TITLE
Laravel 8.x cannot be installed

### ISSUE THREAD

**Issue by siaoynli** [php-casbin/laravel-authz#5]
Laravel 8.x cannot be installed

**Comment by techoner** [comment]
We will support Laravel 8 soon.

**Comment by rus-ik** [comment]
Guys, do you have any updates about the ETA of v.8 support? Thanks in advance..

**Comment by hsluoyz** [comment]
@techoner

**Comment by zhimma** [comment]
坐等。。。

**Comment by hsluoyz** [comment]
@siaoynli fixed in: https://github.com/php-casbin/laravel-authz/pull/8
