### ISSUE TITLE
¿Multiple policy definition?

### ISSUE THREAD

**Issue by bpuig** [php-casbin/laravel-authz#52]
Hello,
I'm on a situation that sometimes I have more parameters for the policies, can this be made like in documentation? I can't figure out the way to make it work. It always tells me I provided less parameters.

[policy_definition]
p = sub, obj, act
p2 = sub, act

Thanks

**Comment by hsluoyz** [comment]
@bpuig why close?

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by bpuig** [comment]
The package won, I was unable to figure anything out about multiple policies and matchers and now my brain is melt 😩

**Comment by hsluoyz** [comment]
@bpuig we recommend using only one p, for your p2, you can leave the `obj` empty

**Comment by bpuig** [comment]
And any suggestion on how to eval() an object? It only allows strings as parameters. Thanks in advance, I've had 2 rough days trying to figure out how everything works

**Comment by leeqvip** [comment]
I recommend you to refer to this tutorial to get started: https://github.com/php-casbin/casbin-tutorials
