### ISSUE TITLE
[Question] Please tell me how to expand the list of functions

### ISSUE THREAD

**Issue by vvistmn** [php-casbin/laravel-authz#54]
HI!

I called the **addFunction** method of the **FunctionMap** class in the controller to create the function. I use **RequestMiddleware**, the  **FunctionMap::loadFunctionMap()** method is called there - which returns a list of commands by default. And there is no my function. Where can I define my function so that it can be seen from the **RequestMiddleware**? Or is it necessary to override the default classes?

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by hsluoyz** [comment]
@vvistmn hi, can you make a PR to fix it?

**Comment by leeqvip** [comment]
@vvistmn 
How to add a customized function: https://casbin.org/docs/function#how-to-add-a-customized-function
You can use facade static calls in this project:
```
Enforcer::addFunction("yourfunction", func customFunctionWrapper(...$args){
     // todo ...
});
```
