### ISSUE TITLE
Policy add command incorrectly inserts policy resulting in error

### ISSUE THREAD

**Issue by timyourivh** [php-casbin/laravel-authz#55]
Package version used: `casbin/laravel-authz: ^3.1` (v3.1.4 in lockfile)

When trying out this package I tried adding a policy using the `policy:add` command. As stated in the documentation found in the README.md: 

<details>

<summary>README.md snippet</summary>

> ### [Using artisan commands](https://github.com/php-casbin/laravel-authz#using-artisan-commands)
> You can create a policy from a console with artisan commands.
> (...)
> To Role::
> ```
> php artisan policy:add writer,articles,edit
> ```

</details>

I ran command `php artisan policy:add admin,posts,index`. This resulted in the following record being inserted:

![image](https://user-images.githubusercontent.com/60601502/223654548-79a8682b-eb73-4596-978c-5f8cdd693235.png)

Which I assumed was incorrect.
It also throws an error when comparing/checking the rule:

![image](https://user-images.githubusercontent.com/60601502/223654790-3f9fff6b-e579-45f9-84ca-4ca5eeb59b7f.png)

I manually changed the rule to the way the Enforcer facade adds it:

![image](https://user-images.githubusercontent.com/60601502/223655698-8f8bbd1d-49f7-44a2-9bb4-a86eb512bf36.png)

Which worked. So I think this is a bug.

---

### Sidenote:

The command `policy:add` implies that it adds a **policy** while `Enforcer::addPermissionForUser()` (which does the same) implies that it adds a **permission** which is inconsistent. I suggest renaming one of the two to match the other.

**Comment by hsluoyz** [comment]
@timyourivh hi, can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@timyourivh The fourth parameter of this command is the policy string, separated by commas(,). I followed your steps, but it didn't reproduce in my console. Which terminal do you use, is it a character problem?

**Comment by timyourivh** [comment]
### Note: 
The docs state that `php artisan vendor:publish` will "will create a new model config file and a new lauthz config file" but instead will display a list of all publishable assets available and launch a prompt to choose one. I suggest adding the tags in the tutorial resulting in:

```
php artisan vendor:publish --tag=laravel-lauthz-config --tag=laravel-lauthz-migrations
```
