### ISSUE TITLE
root for rbac with all pattern model can not pass the verify. But the casbin editor does.

### ISSUE THREAD

**Issue by oknixus** [php-casbin/laravel-authz#59]
My codes:
```
    // adds permissions to a user
    Enforcer::addPermissionForUser('admin', 'article', 'content', 'read');
    Enforcer::addPermissionForUser('admin', 'goods', 'content', 'write');

    Enforcer::addPermissionForUser('root', '*', '*', '*');

    // adds a role for a user.
    Enforcer::addRoleForUser('eve', 'root', '*');
    Enforcer::addRoleForUser('bob', 'admin', '*');
    Enforcer::addRoleForUser('tom', 'admin', 'goods');

    if (Enforcer::enforce("eve", "article", "content", "read")) {
        return sprintf('yes. %s', now()->format('Y-m-d H:i:s'));
    }

    if (Enforcer::enforce("bob", 'goods', 'content', 'read')) {
        return sprintf('bob has this perm. %s', now()->format('Y-m-d H:i:s'));
    }

    if (Enforcer::enforce('tom', 'goods', 'content', 'write')) {
        return sprintf('this is tom. %s', now()->format('Y-m-d H:i:s'));
    }
```
Enforcement result in my requests, only the last one without `*` passed enforcement:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/4592706/226863075-2d07a8dc-1d82-4096-aca4-1fb831eb161f.png">

## In the casbin editor:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/4592706/226867088-46a3e9ff-5fc5-47d6-a838-fc54f1d7a6ba.png">

## I found the dom can't use the pattern.
If I change the code to(**_use '*' instead of 'article'_**):
```
    if (Enforcer::enforce("eve", "*", "content", "read")) {
        return sprintf('yes. %s', now()->format('Y-m-d H:i:s'));
    }
```
It works fine:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/4592706/226868603-7d38683c-88a2-4f0d-a2c9-cd669ccf99cf.png">

**Comment by hsluoyz** [comment]
@oknixus this is possible because Casbin Editor is powered by Node.js version Casbin: https://github.com/casbin/casbin-editor , however, this repo is powered by PHP version Casbin

@leeqvip any ideas?

**Comment by oknixus** [comment]
Thanks very much!

**Comment by oknixus** [comment]
So need I implement it myself? Such as : `Enforcer::hasRoleForUser('eve', 'root', '*')`

**Comment by oknixus** [comment]
I could implement the global super user permission via `Enforcer::hasRoleForUser($userId, 'root', '*')`, but I can't implement the local super user permission. 
eg: There are two module named `article` and `goods`, some user need all permissions in `article` or `goods`.

**Comment by oknixus** [comment]
I add this `!Enforcer::enforce($userId, '*', $model, $action)` in the middleware,  implement the local super user permissions.

**Comment by hsluoyz** [comment]
@oknixus glad to see that you have resolved the issue. Why open again?

**Comment by oknixus** [comment]
I resolved too rough. Expect your elegant solution.😄

**Comment by oknixus** [comment]
Well……I'd better close this issue. Thanks very much.

**Comment by leeqvip** [comment]
@oknixus refer to this: [Super Admin](https://casbin.org/docs/superadmin)

**Comment by oknixus** [comment]
@leeqvip No. I'm afraid there's a problem in your matchers: 
The `admin` only have the permission `write` for `goods`.  In your matchers, `bob` have `read` permission for the `content` of `goods`. This expends the permissions of `bob`.

**Comment by oknixus** [comment]
Well……my code also is wrong:
```
if (
            (
                !Enforcer::enforce($userId, $module, $model, $action)
                && !Enforcer::enforce($userId, '*', $model, $action)
            )
            && !Enforcer::hasRoleForUser($userId, 'root', '*')
        ) {
            return \response()->json(['msg' => '无操作权限']);
        }
```

**Comment by oknixus** [comment]
I think my matchers is wrong. This package is ok.
