### ISSUE TITLE
Error Connection on lumen.laravel 8.x

### ISSUE THREAD

**Issue by numstar** [php-casbin/laravel-authz#60]
![image](https://user-images.githubusercontent.com/3045840/228742583-144b3bdd-8b5e-4a63-a5b2-8c197a3847ac.png)

I use this config
'database' => [
    // Database connection for following tables.
    'connection' => '',
    // Rule table name.
    'rules_table' => 'tbl_roles',
],

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@numstar  Have you enabled `Eloquent` in lumen?

**Comment by numstar** [comment]
enabled Eloquent It work thank you.

**Comment by hsluoyz** [comment]
@numstar plz close issue if resolved
