### ISSUE TITLE
How to modify the creation time and update time field names

### ISSUE THREAD

**Issue by Xanyone** [php-casbin/laravel-authz#61]
The official document of larravel defines const coverage in the model, but we need to create our own data table, change the creation time and update time fields to createTime and updateTime. Can we add created in the configuration file_ At for repair

**Comment by hsluoyz** [comment]
@leeqvip

**Comment by leeqvip** [comment]
@Xanyone You can [Binding A Singleton](https://laravel.com/docs/10.x/container#binding-a-singleton) for `DatabaseAdapter`:

```php
$this->app->singleton(DatabaseAdapter::class, function (Application $app) {
    return new DatabaseAdapter($app->make(YourRule::class));
});
```
