### ISSUE TITLE
Performance feedback

### ISSUE THREAD

**Issue by outsource-zone** [php-casbin/laravel-authz#67]
If there are many permission points, time out may occur. You are advised to add rules in batches.

**Comment by leeqvip** [comment]
[PHP-Casbin](https://github.com/php-casbin/php-casbin) provides some batch adding methods, such as:
```php
Enforcer::addPolicies([...]);
```
Please refer to: https://casbin.org/docs/management-api#addpolicies

**Comment by outsource-zone** [comment]
Oh, it's very useful to me. Thank you.

**Comment by hsluoyz** [comment]
@outsource-zone  @leeqvip this issue can be closed
