### ISSUE TITLE
Unable to use FileAdapter adapter

### ISSUE THREAD

**Issue by mouyong** [php-casbin/laravel-authz#7]

**Comment by hsluoyz** [comment]
@techoner @yk17310320725

**Comment by techoner** [comment]
@mouyong You can specify adapter in the configuration file: https://github.com/php-casbin/laravel-authz#multiple-enforcers

**Comment by mouyong** [comment]
@techoner it's need users write CasbinFileAdapter ?

![image](https://user-images.githubusercontent.com/10336437/108453061-a302ba00-72a4-11eb-85f7-b5c89cc1d283.png)

![image](https://user-images.githubusercontent.com/10336437/108453073-ab5af500-72a4-11eb-8937-ede35e9e9f72.png)

**Comment by mouyong** [comment]
when i use FileAdapter, it have some exceptioin.

![image](https://user-images.githubusercontent.com/10336437/108471741-cd656f00-72c6-11eb-925b-81b65119f20e.png)

![image](https://user-images.githubusercontent.com/10336437/108471764-d5bdaa00-72c6-11eb-825e-03341c9893ec.png)

because in \Lauthz\EnforcerManager:97-99, not resolve by different adapter.

![image](https://user-images.githubusercontent.com/10336437/108471872-fc7be080-72c6-11eb-9b0a-9282ebfdc54a.png)

**Comment by hsluoyz** [comment]
@techoner
