### ISSUE TITLE
Enforcer::getAllRoles() Function Does Not Exist

### ISSUE THREAD

**Issue by swarakaka** [php-casbin/laravel-authz#76]
The method Enforcer::getAllRoles() is being referenced in the code, but it does not exist in the current version of the Enforcer library. This results in an error when attempting to call the method, breaking functionality related to role management.

**Comment by leeqvip** [comment]
@swarakaka 
Can you provide more detailed information?
It works fine with unit tests.

![image](https://github.com/user-attachments/assets/35ab2ada-50c5-4bad-8cd5-19840146adfb)

**Comment by swarakaka** [comment]
Hello @leeqvip,
as shown in the following two screenshots the method is undefined.

![Screenshot 2024-12-05 at 20 11 45](https://github.com/user-attachments/assets/332f5670-02e6-4782-803e-81f577f90d3d)
![Screenshot 2024-12-05 at 20 14 00](https://github.com/user-attachments/assets/1bcfaef3-b567-4669-b545-ac2ddb6f27bc)

**Note: I am using Laravel**

**Comment by swarakaka** [comment]
Also, if we look at [Facade](https://github.com/php-casbin/laravel-authz/blob/master/src/Facades/Enforcer.php), there is no annotation defined

**Comment by leeqvip** [comment]
@swarakaka Merged, Update and try again?
